# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='TEST', max_length=200),
            preserve_default=False,
        ),
    ]
